name: 0xawaz_tsbtool
services:
  db:
    container_name: "db"
    image: timescale/timescaledb:2.15.3-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: on-failure

  migration:
    container_name: "migration"
    image: postgres:alpine3.16
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "sleep 10 && /migrate.sh"]
    volumes:
      - ./migrate.sh:/migrate.sh
      - ./migrations:/migrations
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  tsbtool:
    container_name: "tsbtool"
    build:
      context: .
      dockerfile: Dockerfile
    image: 0xawaz/tsbtool:0.1.0
    depends_on:
      - db
      - migration
    entrypoint: ["/bin/sh", "-c", "sleep 15 && /app/tsbtool /app/query_params.csv --workers 4"]
    volumes:
      - ./migrations/query_params.csv:/app/query_params.csv
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB_URL: "${POSTGRES_DB_URL}"
      TIMESCALE_DB: "${TIMESCALE_DB}"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${TIMESCALE_DB}"
