version: '3'

services:
  db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: timescale/timescaledb:2.15.3-pg16
    ports:
      - "5432:5432"
